spring:
  banner:
    location: classpath:banner.txt
  threads:
    virtual:
      enabled: true  # 开启虚拟线程
  data:
    redis:
      host: localhost
      port: 6379
      #      password:
      #      username:
      database: 0      # 数据库索引（默认为0）
      timeout: 1800000 # 连接超时时间（毫秒）

  cloud:
    # gateway 配置
    gateway:
      #跨域设置
      globalCors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            exposedHeaders: "Content-Disposition,Content-Type,Cache-Control"
      #g开启服务注册和发现
      discovery:
        locator:
          #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          enabled: true
          #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了
          lowerCaseServiceId: true
          #另一种写法
          #lower-case-service-id: true
      #路由配置
      routes:
        # nacos中的服务1（每个服务中可集群多个应用，可在nacos中配置与治理）
        - id: im-connect # 长连接服务
          uri: lb:ws://im-connect
          predicates:
            - Path=/im/**

        - id: im-meet # 多人会议服务
          uri: lb:ws://im-meet
          predicates:
            - Path=/meet/**

        - id: im-service # 业务处理服务
          uri: lb://im-service
          predicates:
            - Path=/service/**
          filters:
            # 去除一个前缀
            - StripPrefix=1

        - id: im-auth  # 鉴权认证服务
          uri: lb://im-auth
          predicates:
            - Path=/auth/**
          filters:
            # 去除一个前缀
            - StripPrefix=1

        - id: im-generator  # id生成服务
          uri: lb://im-generator
          predicates:
            - Path=/gen/**

        - id: im-update  # id生成服务
          uri: lb://im-update
          predicates:
            - Path=/up/**
          filters:
            # 去除一个前缀
            - StripPrefix=1

        - id: im-file  # id生成服务
          uri: lb://im-file
          predicates:
            - Path=/upload/**
          filters:
            # 去除一个前缀
            - StripPrefix=1



# TODO: log settings
logging:
  config: classpath:logback-plus.xml  #日志配置文件，会在当前项目下去找日志配置文件
  level:
    org.springframework: warn

