server:
  compression:
    enabled: true #  开启gzip压缩
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024

spring: #springboot的配置
  banner:
    location: classpath:banner.txt
  profiles:
    include: undertow  # 引用其他的yml文件
  threads:
    virtual:
      enabled: true  # 开启虚拟线程
  servlet:
    multipart:
      max-file-size: 100MB
  data:
    redis:
      host: localhost
      port: 6379
      password:
      username:

minio:
  endpoint: http://192.168.31.166:9000 #内网地址
  extranet: http://192.168.31.166:9000  #外网访问地址
  #public: http://dns.kizhou.cn:11144  #外网访问地址
  accesskey: admin
  secretkey: admin123
  bucketName: box-im


# TODO: log settings
logging:
  config: classpath:logback-plus.xml  #日志配置文件，会在当前项目下去找日志配置文件
  level:
    com.xy.*.mapper: debug
    com.xy.*: debug
    org.springframework: warn


watermark:
    word: Lucky
    font: Arial